name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Test all services
        run: |
          for d in services/*; do
            echo "==> Testing $d"
            (cd "$d" && go test ./...)
          done

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images (no push)
        run: |
          for d in services/*; do
            name=$(basename "$d")
            docker build -t peerprep/$name:ci "$d"
          done
