services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo-seed:
    image: mongo:7
    depends_on:
      - mongo
    volumes:
      - ./seeds:/seeds:ro
    command: >
      bash -lc "
        sleep 10 &&
        mongosh 'mongodb://mongo:27017/peerprep' /seeds/questions.seed.js
      "
    restart: "no"

volumes:
  mongo-data:
  postgres-data:
