global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "ecs-cluster"
    environment: "dev"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # User Service
  - job_name: "user-service"
    metrics_path: /api/v1/users/metrics
    static_configs:
      - targets: ["user.dev.peerprep-dev.local:8080"]
        labels:
          service: "user"

  # Question Service
  - job_name: "question-service"
    metrics_path: /api/v1/questions/metrics
    static_configs:
      - targets: ["question.dev.peerprep-dev.local:8080"]
        labels:
          service: "question"

  # Match Service
  - job_name: "match-service"
    metrics_path: /api/v1/match/metrics
    static_configs:
      - targets: ["match.dev.peerprep-dev.local:8080"]
        labels:
          service: "match"

  # Collab Service
  - job_name: "collab-service"
    metrics_path: /api/v1/collab/metrics
    static_configs:
      - targets: ["collab.dev.peerprep-dev.local:8080"]
        labels:
          service: "collab"

  # Voice Service
  - job_name: "voice-service"
    metrics_path: /api/v1/voice/metrics
    static_configs:
      - targets: ["voice.dev.peerprep-dev.local:8085"]
        labels:
          service: "voice"
